cd /home/saqibcephsharedvol2/ERLab/IRL_Project/sacae_rs/
python3 train_suite.py \
--domain_name="Lift" \
--robots "Panda" \
--controller="OSC_POSE" \
--save_tb \
--save_video \
--image_size=84 \
--num_layers=4 \
--frame_stack=3 \
--action_repeat=1 \
--horizon=100 \
--init_steps=1000 \
--eval_freq=50000 \
--num_eval_episodes=1 \
--video_save_freq=100000 \
--work_dir='./logdir/' \
--train_camera_names "agentview" \
--render_camera_names "frontview" \
--replay_buffer_capacity=1000001 \
--num_train_steps=1000001